### ISSUE TITLE
crawl data for issues

### ISSUE THREAD

**Issue by nikign** [boyzhirui/CSC510-Project2#5]

**Comment by nikign** [comment]
get number of opened, closed, labeled, commented issues for each person

**Comment by lintingxue** [comment]
1. issues per person
2. # of unclosed issues
3. # of comments per issue
4. # of labels per issue
5. time per issue last (open and closed time)
6. frequency of issue

**Comment by boyzhirui** [comment]
calculate # of comments for each user

**Comment by lintingxue** [comment]
Linting have done this part and analyzed the data.
